---
apiVersion: v1
kind: Pod
metadata:
  name: apiserver-demo
  namespace: scdemo
  labels:
    app: ubunutu-apiserver-demo
    environment: prod
spec:
  automountServiceAccountToken: false
  containers:
  - name: scdemo-apiserver-demo
    image: uptycsk8s-docker-local.jfrog.io/jfrog-test/apiserver-demo:110
    securityContext:
      allowPrivilegeEscalation: false