# General Configuration Options
ci_runner: jenkins
hostname: scdev.uptycs.dev
verbose: false
customer_id: 9c30b0cd-ae68-48ab-a122-b1678e5dd5cb

# Configure vulnerability scanning.
vulnerabilities:
    fatal_cvss_score: 7  # Configure the maximum allowable CVSS score.
    ignore_no_fix: false # Ignore any detected vulnerabilities for which there are no known fixes.
    ignore_packages: []  # A list of packages to ignore any detected vulnerabilities in.
    grace_period: 7d     # Configure a grace period for newly detected vulns

# Configure secrets scanning.
secrets:
    paths:         # Configure paths to scan for secrets.
        - /%%

