# General Configuration Options
ci_runner: jenkins
hostname: devk8con.uptycs.dev
verbose: false
customer_id: 1e9800d9-479b-4345-99bb-b177d22362dc

# Configure vulnerability scanning.
vulnerabilities:
    fatal_cvss_score: 7  # Configure the maximum allowable CVSS score.
    ignore_no_fix: false # Ignore any detected vulnerabilities for which there are no known fixes.
    ignore_packages: []  # A list of packages to ignore any detected vulnerabilities in.
    grace_period: 7d     # Configure a grace period for newly detected vulns

# Configure secrets scanning.
secrets:
    paths:         # Configure paths to scan for secrets.
        - /%%

