# General Configuration Options
ci_runner: jenkins
hostname: supplychaindev.uptycs.dev
verbose: false
customer_id: 2053a0b2-84cc-42c2-8ae6-62c1a8b5915c

# Configure vulnerability scanning.
vulnerabilities:
    fatal_cvss_score: 7  # Configure the maximum allowable CVSS score.
    ignore_no_fix: false # Ignore any detected vulnerabilities for which there are no known fixes.
    ignore_packages: []  # A list of packages to ignore any detected vulnerabilities in.
    grace_period: 7d     # Configure a grace period for newly detected vulns

# Configure secrets scanning.
secrets:
    paths:         # Configure paths to scan for secrets.
        - /%%

